### ISSUE TITLE
Improve Property Finder

### ISSUE THREAD

**Issue by stevevance** [ChicagoCityscape/website#271]
It's currently difficult to review a table of PF properties, or to filter the ones on the map, or to export them. 

# Discussion

All layers should be contributing their data to a single table below the map. The user will be able to search through the results, similar to how one can search the search results on the Search page.

The typical export buttons for Pro users will be at the bottom of the table. 

To improve performance we can grab the first 100 at a time (from each layer) and then the next and previous buttons can be used, with event triggers, to grab the next 100 items (from each layer). This would be a kind of semi-manual SSP. There would need to be a lot of custom DataTables code to manipulate the multiple APIs that fetch data for the Property Finder.

## TODO
- [ ] point to new CCLBA table
- [ ] fix Place selector bug
- [ ] add financial incentives checkboxes

# Other ideas
A radical redesign could have a vertical toolbar on the left side and then a "full screen" map on the right side. The user would be able to switch between map and table views.

**Comment by stevevance** [comment]
Since this hasn’t been addressed in a while; a provisional feature would be to build a map that only finds Vacant Parcels by Place.
